FROM node:6
RUN apt-get update && apt-get install -y ffmpeg
RUN npm install -g https://github.com/Tecaa/hls-live-thumbnails

RUN echo 'export PATH=$PATH:/usr/local/lib/node_modules/hls-live-thumbnails/src/' >> /etc/profile
RUN /bin/bash -c "source /etc/profile"

CMD hls-live-thumbnails --secret "super-secret" --endless --initialThumbnailCount 1 --width 300 --interval 10 --port 4001
EXPOSE 4001