FROM node:6
RUN apt-get install ffmpeg
RUN npm install -g https://github.com/Tecaa/hls-live-thumbnails



CMD hls-live-thumbnails --secret "super-secret" --endless --initialThumbnailCount 1 --width 300 --interval 10