version: '3'
services:
  thumbnails-generator:
    build: ./generator
    container_name: thumbnails-generator
    ports:
     - "8080:8080"
    volumes:
      - "./generator/output:/code/output"
  #thumbnails-server:
    #image: "redis:alpine"
    #volumes:
      #- "./server/output:/code/output"
    #container_name: thumbnails-server
    #ports:
#     - "4000:4000"