version: '3'
services:
  thumbnails-generator:
    build: ./generator
    container_name: thumbnails-generator
    ports:
     - "4001:4001"
    volumes:
      - "/output:/output"
  thumbnails-server:
    build: ./server
    volumes:
      - "/output:/output"
    container_name: thumbnails-server
    ports:
     - "4000:4000"